version: 2.1
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
jobs:
  build:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - run: npm --prefix frontend install
      - persist_to_workspace:
          root: /tmp/crazy-cat
          paths:
            - frontend/dist
            - firebase.json
            - .firebaserc
            - firestore.rules
            - firestore.indexes.json
  deploy:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - attach_workspace:
          at: /tmp/crazy-cat
      - firebase-deploy/deploy:
          token: $token

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

