
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2

version: 2.1
jobs:
  myjob:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - firebase-deploy/deploy:
          token: ${token}

#workflows:
#  "Build And Deploy":
#    commands:
#      - firebase-deploy/deploy:
#          token: ${token}